### ISSUE TITLE
Background value of output cube is 1.

### ISSUE THREAD

**Issue by IanHeywood** [Mulan-94/smops#3]
I ran smops but the interpolated model cube that it produced has a background of 1 instead of 0. I had a look at the code but couldn't see where this originated from.

**Comment by Mulan-94** [comment]
Hi @IanHeywood thanks for this report. Is this happening with all images you run?

**Comment by IanHeywood** [comment]
I've run it twice now and it's happened both times.

**Comment by Athanaseus** [comment]
Getting the same issue with the latest release version `0.1.4`.

**Comment by o-smirnov** [comment]
@Mulan-94 any updates?

**Comment by Mulan-94** [comment]
Yeah, it's under investigation.

**Comment by o-smirnov** [comment]
OK so I'm not trying it yet. :)

**Comment by o-smirnov** [comment]
I think here you create a masked array with ==0 values in the model masked out, right: https://github.com/Mulan-94/smops/blob/main/smops/smooth.py#L190

I would look into what the "fill value" of the masked array is, maybe it's 1 by default? You can probably manually set masked values to 0 before writing out the result.

**Comment by o-smirnov** [comment]
Might actually be as simple as ``np.ma.set_fill_value(beta, 0)``. Or just ``beta.fill_value = 0``.

**Comment by Mulan-94** [comment]
@Athanaseus @IanHeywood @o-smirnov. This seems to now be fixed in the issue-3 branch. Please let me know if it works for you as well. I will then make a new release

**Comment by IanHeywood** [comment]
I can confirm that this is now fixed, thanks @Mulan-94
