### ISSUE TITLE
Issue with WSCLEAN V3.5

### ISSUE THREAD

**Issue by abhisek176** [Mulan-94/smops#8]
I am running smops on wsclean v3.5 outputs and having the following issue:

 14:34:51 29.08.2024 : smops - INFO - Starting frequency interpolation         
 Traceback (most recent call last):                                            
   File "/usr/local/bin/smops", line 8, in <module>                            
     sys.exit(main())                                                          
   File "/usr/local/lib/python3.8/dist-packages/smops/smooth.py", line 388, in 
main                                                                            
     mod_out = interp_cube(model, w_sums, input_center_freqs,                  
   File "/usr/local/lib/python3.8/dist-packages/smops/smooth.py", line 218, in 
interp_cube                                                                     
     np.linalg.solve(hess_comps, dirty_comps),                                 
   File "<__array_function__ internals>", line 200, in solve                   
   File "/usr/local/lib/python3.8/dist-packages/numpy/linalg/linalg.py", line  
386, in solve                                                                   
     r = gufunc(a, b, signature=signature, extobj=extobj)                      
   File "/usr/local/lib/python3.8/dist-packages/numpy/linalg/linalg.py", line  
89, in _raise_linalgerror_singular                                              
     raise LinAlgError("Singular matrix")                                      
 numpy.linalg.LinAlgError: Singular matrix 

However, it works well on the same MS/output images created with WSCLEAN v3.3.

Is this a known issue or a solution available for this?

Thanks very much.

Update: seems like the new version of wsclean v3.5 does not generate 'WSCVWSUM', hence the error. I will raise this issue with wsclean.

**Comment by o-smirnov** [comment]
So what was the issue? Or was it just a null model or something?

@Mulan-94 could probably catch that exception, and print out a friendlier error.

**Comment by abhisek176** [comment]
w_sums array returns null as the header value 'WSCVWSUM' is 0 in the model images, and hence the singular matrix. Seems like something is not working in wsclean v3.5 while calculating the sum-of-visibility-weights and putting it in the header!...

**Comment by o-smirnov** [comment]
Aha, thanks very much for digging into this! It's probably worth raising an issue on the wsclean repo -- and still worth adding an exception handler in smops.
